source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'APExpandingTextView_Example', :exclusive => true do
  pod "APExpandingTextView", :path => "../"
end

target 'APExpandingTextView_Tests', :exclusive => true do
  pod "APExpandingTextView", :path => "../"

  
end
